export const workers = [
  {
    n: 'Atlas',
    short: 'CEO',
    en: 'CEO / Co-founder',
    c: '#788cb5',
    trait: 'Leads company strategy and balances growth, people, and cash flow',
    task: 'Reviewing business reports and coordinating team decisions',
    prop: 'tablet',
  },
  {
    n: 'Nova',
    short: 'Supplier QC',
    en: 'Supplier Quality & Compliance',
    c: '#de9862',
    trait: 'Verifies supplier credentials, product quality, and compliance',
    task: 'Inspecting samples and supplier compliance checklists',
    prop: 'sample',
  },
  {
    n: 'Pixel',
    short: 'Marketplace',
    en: 'Marketplace Channels Lead',
    c: '#9484c2',
    trait:
      'Manages marketplace traffic, product rankings, and channel conversion',
    task: 'Checking marketplace listings and channel campaigns',
    prop: 'tablet',
  },
  {
    n: 'Coco',
    short: 'DTC',
    en: 'DTC & Marketplace Lead',
    c: '#d58091',
    trait:
      'Coordinates products, pricing, and customer experience across DTC and marketplaces',
    task: 'Reviewing DTC and marketplace conversion',
    prop: 'tablet',
  },
  {
    n: 'Echo',
    short: 'Marketing',
    en: 'Marketing Manager',
    c: '#65afb0',
    trait:
      'Leads advertising, creator partnerships, and content with a focus on acquisition cost',
    task: 'Reviewing ad creative, creator partnerships, and the content calendar',
    prop: 'tablet',
  },
  {
    n: 'Finn',
    short: 'Supply Chain',
    en: 'Supply Chain Manager',
    c: '#70a58b',
    trait: 'Coordinates purchasing, inventory, freight, and delivery',
    task: 'Checking shipments, inventory, and replenishment plans',
    prop: 'parcel',
  },
  {
    n: 'Scout',
    short: 'Support',
    en: 'Customer Service Lead',
    c: '#bbab71',
    trait:
      'Leads US and Canadian customer support and keeps delivery promises on track',
    task: 'Handling customer calls and US and Canadian support tickets',
    prop: 'headset',
  },
  {
    n: 'Bolt',
    short: 'People & Ops',
    en: 'People & Ops Manager',
    c: '#679dc4',
    trait: 'Coordinates staffing, hiring, and day-to-day operations',
    task: 'Reviewing team schedules and operational tasks',
    prop: 'clipboard',
  },
  {
    n: 'Stack',
    short: 'Data',
    en: 'Data / Analytics Engineer',
    c: '#a49271',
    trait:
      'Maintains reliable business data and tests assumptions with analysis',
    task: 'Checking data pipelines and business analytics',
    prop: 'tablet',
  },
  {
    n: 'Sage',
    short: 'Finance',
    en: 'Finance Manager',
    c: '#94a0b4',
    trait: 'Tracks costs, margins, and cash flow while managing spending risk',
    task: 'Reconciling budgets, invoices, and order margins',
    prop: 'clipboard',
  },
] as const;
